version: '3.8'

services:
  postgres:
    image: postgres:13.7
    container_name: postgres
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg_data:/var/lib/postgresql/data
